list(APPEND WELD_SYMBOL_NAMES
  AdapterEnumerateFeatures
  AdapterGetLimits
  AdapterGetProperties
  AdapterRelease
  AdapterRequestDevice
  CommandBufferRelease
  CommandEncoderBeginRenderPass
  CommandEncoderFinish
  CommandEncoderRelease
  CreateInstance
  DeviceCreateCommandEncoder
  DeviceEnumerateFeatures
  DeviceGetLimits
  DeviceGetQueue
  DeviceRelease
  DeviceSetUncapturedErrorCallback
  InstanceCreateSurface
  InstanceRelease
  InstanceRequestAdapter
  QueueRelease
  QueueSubmit
  RenderPassEncoderEnd
  RenderPassEncoderRelease
  SurfaceConfigure
  SurfaceGetCurrentTexture
  SurfaceGetPreferredFormat
  SurfacePresent
  SurfaceRelease
  SurfaceUnconfigure
  TextureCreateView
  TextureGetFormat
  TextureViewRelease)
