macro(_target_get_linked_libraries_in _target _outlist)
    list(APPEND "${_outlist}" "${_target}")

    # get libraries
    get_target_property(target_type "${_target}" TYPE)
    if (${target_type} STREQUAL "INTERFACE_LIBRARY")
        get_target_property(libs "${_target}" INTERFACE_LINK_LIBRARIES)
    else()
        get_target_property(libs "${_target}" LINK_LIBRARIES)
    endif()

    foreach(lib IN LISTS libs)
        if(NOT TARGET "${lib}")
            continue()
        endif()
        list(APPEND "${_outlist}" "${lib}")
        _target_get_linked_libraries_in("${lib}" "${_outlist}")
    endforeach()
endmacro()

function(_target_get_linked_libraries _target _outlist)
    set(${_outlist} "${_target}")
    _target_get_linked_libraries_in(${_target} ${_outlist})
    list(REMOVE_DUPLICATES ${_outlist})
    set(${_outlist} ${${_outlist}} PARENT_SCOPE) 
endfunction()
